apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 15672
              name: dashboard
            - containerPort: 5672
              name: api
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-data
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-data-claim
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
    - port: 15672
      name: dashboard
    - port: 5672
      name: api
  selector:
    app: rabbitmq
