---
kind: Service
apiVersion: v1
metadata:
  name: odoo-service
spec:
  selector:
    app: odoo
  ports:
    - port: 8069
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odoo-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: odoo-service
                port:
                  number: 8069