apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/odoo-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-data-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi