apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-deployment
  labels:
    app: odoo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      initContainers:
        - name: chown
          image: busybox
          command: ["/bin/sh", "-c", "chown 101:101 /odoo"]
          volumeMounts:
            - name: odoo-data
              mountPath: /odoo
      containers:
        - name: odoo
          image: odoo:17.0
          ports:
          - containerPort: 8069
          env:
          - name: HOST
            value: postgres
          - name: USER
            value: user
          - name: PASSWORD
            value: password
          volumeMounts:
            - mountPath: /var/lib/odoo
              name: odoo-data
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
      volumes:
        - name: odoo-data
          persistentVolumeClaim:
            claimName: odoo-data-claim